export const languages = {
  en: {
    'MESSAGE_CONFIRM_LOCATION': 'Check your location',
    'MESSAGE_ASK_LOCATION': 'Input your location here',
    'CONFIRM': 'confirm',
    'CHANGE': 'change',
    'CANCEL': 'cancel',
    'SOME FEATURES ARE CURRENTLY UNAVAILABLE': 'Sorry, some features are currently unavailable',
    'NO_SEARCH': 'Search failed',
    'NO_LOCATION': 'Sorry, unable to determine your location',
    'NO_CITY_TRANSLATE': 'Failed to get translation for locality name',
    'NO_BACKGROUND': 'Failed to load background images',
    'NO_FORECAST': 'The weather forecast is not available now, try again later',
    'NO VOICE': 'Your browser does not support pronunciation functions for the selected language, the language will be used',
    'NO RECOGNITION': 'Your browser do not supports speech recognition',
    'LATITUDE': 'Latitude',
    'LONGITUDE': 'Longitude',
    'SEARCH PLACEHOLDER': 'Search city...',
    'SEARCH SUBMIT': 'search',
    'VOLUME SET': 'Volume set',
    'DAY0': 'Sun',
    'DAY1': 'Mon',
    'DAY2': 'Tue',
    'DAY3': 'Wed',
    'DAY4': 'Thu',
    'DAY5': 'Fri',
    'DAY6': 'Sat',
    'FULLDAY0': 'Sunday',
    'FULLDAY1': 'Monday',
    'FULLDAY2': 'Tuesday',
    'FULLDAY3': 'Wednesday',
    'FULLDAY4': 'Thursday',
    'FULLDAY5': 'Friday',
    'FULLDAY6': 'Saturday',
    'MPS': 'm/s',
    'FEELS': 'Feels like',
    'WIND': 'Wind',
    'HUMIDITY': 'Humidity',
    '1000day' : 'Sunny',
    '1003day' : 'Partly Cloudy',
    '1006day' : 'Cloudy',
    '1009day' : 'Overcast',
    '1030day' : 'Mist',
    '1063day' : 'Patchy rain nearby',
    '1066day' : 'Patchy snow nearby',
    '1069day' : 'Patchy sleet nearby',
    '1072day' : 'Patchy freezing drizzle nearby',
    '1087day' : 'Thundery outbreaks in nearby',
    '1114day' : 'Blowing snow',
    '1117day' : 'Blizzard',
    '1135day' : 'Fog',
    '1147day' : 'Freezing fog',
    '1150day' : 'Patchy light drizzle',
    '1153day' : 'Light drizzle',
    '1168day' : 'Freezing drizzle',
    '1171day' : 'Heavy freezing drizzle',
    '1180day' : 'Patchy light rain',
    '1183day' : 'Light rain',
    '1186day' : 'Moderate rain at times',
    '1189day' : 'Moderate rain',
    '1192day' : 'Heavy rain at times',
    '1195day' : 'Heavy rain',
    '1198day' : 'Light freezing rain',
    '1201day' : 'Moderate or heavy freezing rain',
    '1204day' : 'Light sleet',
    '1207day' : 'Moderate or heavy sleet',
    '1210day' : 'Patchy light snow',
    '1213day' : 'Light snow',
    '1216day' : 'Patchy moderate snow',
    '1219day' : 'Moderate snow',
    '1222day' : 'Patchy heavy snow',
    '1225day' : 'Heavy snow',
    '1237day' : 'Ice pellets',
    '1240day' : 'Light rain shower',
    '1243day' : 'Moderate or heavy rain shower',
    '1246day' : 'Torrential rain shower',
    '1249day' : 'Light sleet showers',
    '1252day' : 'Moderate or heavy sleet showers',
    '1255day' : 'Light snow showers',
    '1258day' : 'Moderate or heavy snow showers',
    '1261day' : 'Light showers of ice pellets',
    '1264day' : 'Moderate or heavy showers of ice pellets',
    '1273day' : 'Patchy light rain in area with thunder',
    '1276day' : 'Moderate or heavy rain in area with thunder',
    '1279day' : 'Patchy light snow in area with thunder',
    '1282day' : 'Moderate or heavy snow in area with thunder',
    '1000night' : 'Clear',
    '1003night' : 'Partly Cloudy',
    '1006night' : 'Cloudy',
    '1009night' : 'Overcast',
    '1030night' : 'Mist',
    '1063night' : 'Patchy rain nearby',
    '1066night' : 'Patchy snow nearby',
    '1069night' : 'Patchy sleet nearby',
    '1072night' : 'Patchy freezing drizzle nearby',
    '1087night' : 'Thundery outbreaks in nearby',
    '1114night' : 'Blowing snow',
    '1117night' : 'Blizzard',
    '1135night' : 'Fog',
    '1147night' : 'Freezing fog',
    '1150night' : 'Patchy light drizzle',
    '1153night' : 'Light drizzle',
    '1168night' : 'Freezing drizzle',
    '1171night' : 'Heavy freezing drizzle',
    '1180night' : 'Patchy light rain',
    '1183night' : 'Light rain',
    '1186night' : 'Moderate rain at times',
    '1189night' : 'Moderate rain',
    '1192night' : 'Heavy rain at times',
    '1195night' : 'Heavy rain',
    '1198night' : 'Light freezing rain',
    '1201night' : 'Moderate or heavy freezing rain',
    '1204night' : 'Light sleet',
    '1207night' : 'Moderate or heavy sleet',
    '1210night' : 'Patchy light snow',
    '1213night' : 'Light snow',
    '1216night' : 'Patchy moderate snow',
    '1219night' : 'Moderate snow',
    '1222night' : 'Patchy heavy snow',
    '1225night' : 'Heavy snow',
    '1237night' : 'Ice pellets',
    '1240night' : 'Light rain shower',
    '1243night' : 'Moderate or heavy rain shower',
    '1246night' : 'Torrential rain shower',
    '1249night' : 'Light sleet showers',
    '1252night' : 'Moderate or heavy sleet showers',
    '1255night' : 'Light snow showers',
    '1258night' : 'Moderate or heavy snow showers',
    '1261night' : 'Light showers of ice pellets',
    '1264night' : 'Moderate or heavy showers of ice pellets',
    '1273night' : 'Patchy light rain in area with thunder',
    '1276night' : 'Moderate or heavy rain in area with thunder',
    '1279night' : 'Patchy light snow in area with thunder',
    '1282night' : 'Moderate or heavy snow in area with thunder',
    'NOT IMPLEMENTED': 'not implemented',

  },
  ru: {
    'MESSAGE_CONFIRM_LOCATION': 'Подтвердите Ваше местоположение',
    'MESSAGE_ASK_LOCATION': 'Введите Ваше местоположение',
    'CONFIRM': 'принять',
    'CHANGE': 'изменить',
    'CANCEL': 'отмена',
    'SOME FEATURES ARE CURRENTLY UNAVAILABLE': 'Некоторые функции сайта недоступны в настоящее время',
    'NO_SEARCH': 'Ничего не найдено',
    'NO_LOCATION': 'Не удалось определить Ваше местоположение',
    'NO_CITY_TRANSLATE': 'Не удалось получить перевод для названия местности',
    'NO_BACKGROUND': 'Не удалось загрузить фоновые изображения',
    'NO_FORECAST': 'Прогноз погоды недоступен сейчас, попробуйте позже',
    'NO VOICE': 'Ваш браузер не поддерживает функции произношения для выбранного языка, будет использован язык',
    'NO RECOGNITION': 'Ваш браузер не поддерживает распознавание речи',
    'LATITUDE': 'Широта',
    'LONGITUDE': 'Долгота',
    'SEARCH PLACEHOLDER': 'Найти город...',
    'SEARCH SUBMIT': 'ПОИСК',
    'VOLUME SET': 'Громкость установлена',
    'DAY0': 'Вс',
    'DAY1': 'Пн',
    'DAY2': 'Вт',
    'DAY3': 'Ср',
    'DAY4': 'Чт',
    'DAY5': 'Пт',
    'DAY6': 'Сб',
    'FULLDAY0': 'Воскресенье',
    'FULLDAY1': 'Понедельник',
    'FULLDAY2': 'Вторник',
    'FULLDAY3': 'Среда',
    'FULLDAY4': 'Четверг',
    'FULLDAY5': 'Пятница',
    'FULLDAY6': 'Суббота',
    'MPS': 'м/с',
    'FEELS': 'Ощущается',
    'WIND': 'Ветер',
    'HUMIDITY': 'Влажность',
    '1000day' : 'Солнечно',
    '1003day' : 'Переменная облачность',
    '1006day' : 'Облачно',
    '1009day' : 'Пасмурно',
    '1030day' : 'Дымка',
    '1063day' : 'Местами дождь',
    '1066day' : 'Местами снег',
    '1069day' : 'Местами дождь со снегом',
    '1072day' : 'Местами замерзающая морось',
    '1087day' : 'Местами грозы',
    '1114day' : 'Поземок',
    '1117day' : 'Метель',
    '1135day' : 'Туман',
    '1147day' : 'Переохлажденный туман',
    '1150day' : 'Местами слабая морось',
    '1153day' : 'Слабая морось',
    '1168day' : 'Замерзающая морось',
    '1171day' : 'Сильная замерзающая морось',
    '1180day' : 'Местами небольшой дождь',
    '1183day' : 'Небольшой дождь',
    '1186day' : 'Временами умеренный дождь',
    '1189day' : 'Умеренный дождь',
    '1192day' : 'Временами сильный дождь',
    '1195day' : 'Сильный дождь',
    '1198day' : 'Слабый переохлажденный дождь',
    '1201day' : 'Умеренный или сильный переохлажденный дождь',
    '1204day' : 'Небольшой дождь со снегом',
    '1207day' : 'Умеренный или сильный дождь со снегом',
    '1210day' : 'Местами небольшой снег',
    '1213day' : 'Небольшой снег',
    '1216day' : 'Местами умеренный снег',
    '1219day' : 'Умеренный снег',
    '1222day' : 'Местами сильный снег',
    '1225day' : 'Сильный снег',
    '1237day' : 'Ледяной дождь',
    '1240day' : 'Кратковременный ливневый дождь',
    '1243day' : 'Умеренный или сильный ливневый дождь',
    '1246day' : 'Сильные ливни',
    '1249day' : 'Кратковременный ливневый дождь со снегом',
    '1252day' : 'Умеренные или сильные ливневые дожди со снегом',
    '1255day' : 'Небольшой снег',
    '1258day' : 'Умеренный или сильный снег',
    '1261day' : 'Небольшой ледяной дождь',
    '1264day' : 'Умеренный или сильный ледяной дождь',
    '1273day' : 'В отдельных районах местами небольшой дождь с грозой',
    '1276day' : 'В отдельных районах умеренный или сильный дождь с грозой',
    '1279day' : 'В отдельных районах местами небольшой снег с грозой',
    '1282day' : 'В отдельных районах умеренный или сильный снег с грозой',
    '1000night' : 'Ясно',
    '1003night' : 'Переменная облачность',
    '1006night' : 'Облачно',
    '1009night' : 'Пасмурно',
    '1030night' : 'Дымка',
    '1063night' : 'Местами дождь',
    '1066night' : 'Местами снег',
    '1069night' : 'Местами дождь со снегом',
    '1072night' : 'Местами замерзающая морось',
    '1087night' : 'Местами грозы',
    '1114night' : 'Поземок',
    '1117night' : 'Метель',
    '1135night' : 'Туман',
    '1147night' : 'Переохлажденный туман',
    '1150night' : 'Местами слабая морось',
    '1153night' : 'Слабая морось',
    '1168night' : 'Замерзающая морось',
    '1171night' : 'Сильная замерзающая морось',
    '1180night' : 'Местами небольшой дождь',
    '1183night' : 'Небольшой дождь',
    '1186night' : 'Временами умеренный дождь',
    '1189night' : 'Умеренный дождь',
    '1192night' : 'Временами сильный дождь',
    '1195night' : 'Сильный дождь',
    '1198night' : 'Слабый переохлажденный дождь',
    '1201night' : 'Умеренный или сильный переохлажденный дождь',
    '1204night' : 'Небольшой дождь со снегом',
    '1207night' : 'Умеренный или сильный дождь со снегом',
    '1210night' : 'Местами небольшой снег',
    '1213night' : 'Небольшой снег',
    '1216night' : 'Местами умеренный снег',
    '1219night' : 'Умеренный снег',
    '1222night' : 'Местами сильный снег',
    '1225night' : 'Сильный снег',
    '1237night' : 'Ледяной дождь',
    '1240night' : 'Кратковременный ливневый дождь',
    '1243night' : 'Умеренный или сильный ливневый дождь',
    '1246night' : 'Сильные ливни',
    '1249night' : 'Кратковременный ливневый дождь со снегом',
    '1252night' : 'Умеренные или сильные ливневые дожди со снегом',
    '1255night' : 'Небольшой снег',
    '1258night' : 'Умеренный или сильный снег',
    '1261night' : 'Небольшой ледяной дождь',
    '1264night' : 'Умеренный или сильный ледяной дождь',
    '1273night' : 'В отдельных районах местами небольшой дождь с грозой',
    '1276night' : 'В отдельных районах умеренный или сильный дождь с грозой',
    '1279night' : 'В отдельных районах местами небольшой снег с грозой',
    '1282night' : 'В отдельных районах умеренный или сильный снег с грозой',
    'NOT IMPLEMENTED': 'не реализовано',

  },
  be: {
    'MESSAGE_CONFIRM_LOCATION': 'Праверце Ваша месцазнаходжанне',
    'MESSAGE_ASK_LOCATION': 'Укажыце Ваша месцазнаходжанне',
    'CONFIRM': 'згадзiцца',
    'CHANGE': 'змянiць',
    'CANCEL': 'адмянiць',
    'SOME FEATURES ARE CURRENTLY UNAVAILABLE': 'Некаторыя функцыi старонкi не працуюць ў дадзены момант',
    'NO_SEARCH': 'Нiчога не знайдзена',
    'NO_LOCATION': 'Не выпала атрымаць Ваша месцазнаходжанне',
    'NO_CITY_TRANSLATE': 'Не атрымалася перавесцi назву мясцiны',
    'NO_BACKGROUND': 'Фотаздымкi для фону не дасягальныя ў дадзены момант',
    'NO_FORECAST': 'Прагноз надвор\'я не недасягальны зараз, паспрабуйце пазней',
    'NO VOICE': 'Ваш браўзер не падтрымлiвае функцыi маўлення для выбраннай мовы, будзе выкарыстана мова',
    'NO RECOGNITION': 'Ваш браўзер не падтрымлiвае функцыi вызначэння маўлення',
    'LATITUDE': 'Шырата',
    'LONGITUDE': 'Даўгата',
    'SEARCH PLACEHOLDER': 'Пошук месца...',
    'SEARCH SUBMIT': 'ПОШУК',
    'VOLUME SET': 'Гучнасць усталявана',
    'DAY0': 'Няд',
    'DAY1': 'Пан',
    'DAY2': 'Аўт',
    'DAY3': 'Сер',
    'DAY4': 'Чац',
    'DAY5': 'Пят',
    'DAY6': 'Суб',
    'FULLDAY0': 'Нядзеля',
    'FULLDAY1': 'Панядзелак',
    'FULLDAY2': 'Аўторак',
    'FULLDAY3': 'Серада',
    'FULLDAY4': 'Чацвер',
    'FULLDAY5': 'Пятнiца',
    'FULLDAY6': 'Субота',
    'MPS': 'м/с',
    'FEELS': 'Адчуваецца',
    'WIND': 'Вецер',
    'HUMIDITY': 'Вiльготнасць',
    '1000day' : 'Сонечна',
    '1003day' : 'Пераменная воблачность',
    '1006day' : 'Воблачна',
    '1009day' : 'Пахмурна',
    '1030day' : 'Дымка',
    '1063day' : 'Месцами дожд',
    '1066day' : 'Месцами снег',
    '1069day' : 'Месцами дожд са снегам',
    '1072day' : 'Месцами золка',
    '1087day' : 'Месцами грозы',
    '1114day' : 'Паземка',
    '1117day' : 'Завiруха',
    '1135day' : 'Туман',
    '1147day' : 'Золка',
    '1150day' : 'Месцами слабая морась',
    '1153day' : 'Слабая морась',
    '1168day' : 'Золка',
    '1171day' : 'Вельмi золка',
    '1180day' : 'Месцами невялiкi дожд',
    '1183day' : 'Невялiкi дожд',
    '1186day' : 'Часам умеранны дожд',
    '1189day' : 'Умеранны дожд',
    '1192day' : 'Часам моцны дожд',
    '1195day' : 'Моцны дожд',
    '1198day' : 'Слабы халодны дожд',
    '1201day' : 'Умеранны або моцны халодны дожд',
    '1204day' : 'Невялiкi дожд са снегам',
    '1207day' : 'Умеранны або моцны дожд са снегам',
    '1210day' : 'Месцами невялiкi снег',
    '1213day' : 'Невялiкi снег',
    '1216day' : 'Месцами умеранны снег',
    '1219day' : 'Умеранны снег',
    '1222day' : 'Месцами моцны снег',
    '1225day' : 'Моцны снег',
    '1237day' : 'Град',
    '1240day' : 'Караткачасовыя лiўнi',
    '1243day' : 'Умеранны або моцны лiвень',
    '1246day' : 'Моцныя лiўнi',
    '1249day' : 'Караткачасовы лиўневы дожд са снегам',
    '1252day' : 'Умеренные або моцныя лiўнi са снегам',
    '1255day' : 'Невялiкi снег',
    '1258day' : 'Умеранны або моцны снег',
    '1261day' : 'Невялiкi град',
    '1264day' : 'Умеранны або моцны град',
    '1273day' : 'У асбных раёнах месцами невялiкi дожд з гразой',
    '1276day' : 'У асбных раёнах умеранны або моцны дожд з гразой',
    '1279day' : 'У асбных раёнах месцами невялiкi снег з гразой',
    '1282day' : 'У асбных раёнах умеранны або моцны снег з гразой',
    '1000night' : 'Ясна',
    '1003night' : 'Пераменная воблачнасць',
    '1006night' : 'Воблачна',
    '1009night' : 'Пасмурна',
    '1030night' : 'Дымка',
    '1063night' : 'Месцами дожд',
    '1066night' : 'Месцами снег',
    '1069night' : 'Месцами дожд са снегам',
    '1072night' : 'Месцами золка',
    '1087night' : 'Месцами грозы',
    '1114night' : 'Паземка',
    '1117night' : 'Завируха',
    '1135night' : 'Туман',
    '1147night' : 'Золка',
    '1150night' : 'Месцами слабая морась',
    '1153night' : 'Слабая морась',
    '1168night' : 'Морась, золка',
    '1171night' : 'Моцная морась, золка',
    '1180night' : 'Месцами невялiкi дожд',
    '1183night' : 'Невялiкi дожд',
    '1186night' : 'Часам умеранны дожд',
    '1189night' : 'Умеранны дожд',
    '1192night' : 'Часам моцны дожд',
    '1195night' : 'Моцны дожд',
    '1198night' : 'Слабы халодны дожд',
    '1201night' : 'Умеранны або моцны халодны дожд',
    '1204night' : 'Невялiкi дожд са снегам',
    '1207night' : 'Умеранны або моцны дожд са снегам',
    '1210night' : 'Месцами невялiкi снег',
    '1213night' : 'Невялiкi снег',
    '1216night' : 'Месцами умеранны снег',
    '1219night' : 'Умеранны снег',
    '1222night' : 'Месцами моцны снег',
    '1225night' : 'Моцны снег',
    '1237night' : 'Град',
    '1240night' : 'Караткачасовы лиўневы дожд',
    '1243night' : 'Умеранны або моцны лиўневы дожд',
    '1246night' : 'Моцныя лiўнi',
    '1249night' : 'Караткачасовы лиўневы дожд са снегам',
    '1252night' : 'Умеренные або моцныя лiўнi са снегам',
    '1255night' : 'Невялiкi снег',
    '1258night' : 'Умеранны або моцны снег',
    '1261night' : 'Невялiкi град',
    '1264night' : 'Умеранны або моцны град',
    '1273night' : 'У асбных раёнах месцами невялiкi дожд з гразой',
    '1276night' : 'У асбных раёнах умеранны або моцны дожд з гразой',
    '1279night' : 'У асбных раёнах месцами невялiкi снег з гразой',
    '1282night' : 'У асбных раёнах умеранны або моцны снег з гразой',
    'NOT IMPLEMENTED': 'не рэалізавана',

  },
}

export default function createTranslator(language: string): (text: string) => string {
  return (text) => {
    return languages[language][text];
  };
}