export const languages = {
  en: {
    'MESSAGE_CONFIRM_LOCATION': 'Check your location',
    'MESSAGE_ASK_LOCATION': 'Input your location here',
    'CONFIRM': 'confirm',
    'CHANGE': 'change',
    'CANCEL': 'cancel',
    'SOME FEATURES ARE CURRENTLY UNAVAILABLE': 'Sorry, some features are currently unavailable',
    'NO_SEARCH': 'Search failed',
    'NO_LOCATION': 'Sorry, unable to determine your location',
    'NO_CITY_TRANSLATE': 'Failed to get translation for locality name',
    'NO_BACKGROUND': 'Failed to load background images',
    'NO_FORECAST': 'The weather forecast is not available now, try again later',
    'LATITUDE': 'Latitude',
    'LONGITUDE': 'Longitude',
    'SEARCH PLACEHOLDER': 'Search city...',
    'SEARCH SUBMIT': 'search',
    'DAY0': 'Sun',
    'DAY1': 'Mon',
    'DAY2': 'Tue',
    'DAY3': 'Wed',
    'DAY4': 'Thu',
    'DAY5': 'Fri',
    'DAY6': 'Sat',
    'FULLDAY0': 'Sunday',
    'FULLDAY1': 'Monday',
    'FULLDAY2': 'Tuesday',
    'FULLDAY3': 'Wednesday',
    'FULLDAY4': 'Thursday',
    'FULLDAY5': 'Friday',
    'FULLDAY6': 'Saturday',
    'MPS': 'm/s',
    'FEELS': 'Feels like',
    'WIND': 'Wind',
    'HUMIDITY': 'Humidity',
  },
  ru: {
    'MESSAGE_CONFIRM_LOCATION': 'Подтвердите Ваше местоположение',
    'MESSAGE_ASK_LOCATION': 'Введите Ваше местоположение',
    'CONFIRM': 'принять',
    'CHANGE': 'изменить',
    'CANCEL': 'отмена',
    'SOME FEATURES ARE CURRENTLY UNAVAILABLE': 'Некоторые функции сайта недоступны в настоящее время',
    'NO_SEARCH': 'Поиск не удался по Вышему запросу',
    'NO_LOCATION': 'Не удалось определить Ваше местоположение',
    'NO_CITY_TRANSLATE': 'Не удалось получить перевод для названия местности',
    'NO_BACKGROUND': 'Не удалось загрузить фоновые изображения',
    'NO_FORECAST': 'Прогноз погоды недоступен сейчас, попробуйте позже',
    'LATITUDE': 'Широта',
    'LONGITUDE': 'Долгота',
    'SEARCH PLACEHOLDER': 'Найти город...',
    'SEARCH SUBMIT': 'ПОИСК',
    'DAY0': 'Вс',
    'DAY1': 'Пн',
    'DAY2': 'Вт',
    'DAY3': 'Ср',
    'DAY4': 'Чт',
    'DAY5': 'Пт',
    'DAY6': 'Сб',
    'FULLDAY0': 'Воскресенье',
    'FULLDAY1': 'Понедельник',
    'FULLDAY2': 'Вторник',
    'FULLDAY3': 'Среда',
    'FULLDAY4': 'Четверг',
    'FULLDAY5': 'Пятница',
    'FULLDAY6': 'Суббота',
    'MPS': 'м/с',
    'FEELS': 'Ощущается',
    'WIND': 'Ветер',
    'HUMIDITY': 'Влажность',
  },
  be: {
    'MESSAGE_CONFIRM_LOCATION': 'Праверце Ваша месцазнаходжанне',
    'MESSAGE_ASK_LOCATION': 'Укажыце Ваша месцазнаходжанне',
    'CONFIRM': 'згадзiцца',
    'CHANGE': 'змянiць',
    'CANCEL': 'адмянiць',
    'SOME FEATURES ARE CURRENTLY UNAVAILABLE': 'Некаторыя функцыi старонкi не працуюць ў дадзены момант',
    'NO_SEARCH': 'Немагчыма нiчога знайсцi па Вашаму запыту',
    'NO_LOCATION': 'Не выпала атрымаць Ваша месцазнаходжанне',
    'NO_CITY_TRANSLATE': 'Не атрымалася перавесцi назву мясцiны',
    'NO_BACKGROUND': 'Фотаздымкi для фону не дасягальныя ў дадзены момант',
    'NO_FORECAST': 'Прагноз надвор\'я не недасягальны зараз, паспрабуйце пазней',
    'LATITUDE': 'Шырата',
    'LONGITUDE': 'Даўгата',
    'SEARCH PLACEHOLDER': 'Пошук месца...',
    'SEARCH SUBMIT': 'ПОШУК',
    'DAY0': 'Няд',
    'DAY1': 'Пан',
    'DAY2': 'Аўт',
    'DAY3': 'Сер',
    'DAY4': 'Чац',
    'DAY5': 'Пят',
    'DAY6': 'Суб',
    'FULLDAY0': 'Нядзеля',
    'FULLDAY1': 'Панядзелак',
    'FULLDAY2': 'Аўторак',
    'FULLDAY3': 'Серада',
    'FULLDAY4': 'Чацвер',
    'FULLDAY5': 'Пятнiца',
    'FULLDAY6': 'Субота',
    'MPS': 'м/с',
    'FEELS': 'Адчуваецца',
    'WIND': 'Вецер',
    'HUMIDITY': 'Вiльготнасць',
  },
}

export default function createTranslator(language: string): (text: string) => string {
  return (text) => {
    return languages[language][text];
  };
}